/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api("org.springframework.boot:spring-boot-starter-web:2.5.5")
    api("org.springframework.boot:spring-boot-starter-validation:2.5.5")
    api("org.springframework.boot:spring-boot-starter-data-jpa:2.5.5")
    api("org.springdoc:springdoc-openapi-starter-webmvc-ui:2.0.0")
    api("org.postgresql:postgresql:42.2.23")
    api("org.springframework:spring-core:6.0.13")
    api("jakarta.validation:jakarta.validation-api:3.0.0")
    api("org.hibernate.validator:hibernate-validator:7.0.2.Final")
    api("jakarta.transaction:jakarta.transaction-api:2.0.0")
    runtimeOnly("com.h2database:h2:1.4.200")
    runtimeOnly("org.springframework.boot:spring-boot-devtools:2.5.5")
    testImplementation("org.springframework.boot:spring-boot-starter-test:2.5.5")
    testImplementation("org.assertj:assertj-core:3.24.2")
    testImplementation("org.hamcrest:hamcrest:2.2")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.10.1")
    testImplementation("org.skyscreamer:jsonassert:1.5.1")
    testImplementation("org.springframework:spring-test:6.0.13")
    compileOnly("jakarta.servlet:jakarta.servlet-api:5.0.0")
    compileOnly("jakarta.persistence:jakarta.persistence-api:3.0.0")
}

group = "com.silovale"
version = "0.0.1-SNAPSHOT"
description = "silovale-api"
java.sourceCompatibility = JavaVersion.VERSION_17

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
